### ISSUE TITLE
Postgraphile doesn't recognize UDFs with "out" keywords instead of "returns"

### ISSUE THREAD

**Issue by w9** [graphile/graphile-engine#175]
Given two equivalent user defined functions (UDF):

```
create function hello(out tax integer) as $$
begin
  tax := 42;
end;
$$
language plpgsql;

create function hello2() returns integer as $$
begin
  return 42;
end;
$$
language plpgsql;
```

Only `hello2` will be recognized and included in the generated schema.

The usage of the `out` keyword is documented [here](https://www.postgresql.org/docs/current/static/plpgsql-declarations.html#PLPGSQL-DECLARATION-PARAMETERS).

**Comment by benjie** [comment]
Yes, we don't have `OUT` support currently - I should add that to the docs.

If you're interested in adding support, I can probably give you some pointers 👍

**Comment by w9** [comment]
@benjie Sure, I would be glad to give it a try.

In the meantime, is there a way to give the returned value an alias? Right now by default the returned value just has the name as the type name.

**Comment by w9** [comment]
@benjie Then I think the `out` keyword is a natural solution to this. You could just have

```
create function hello(out foo integer, out bar text) ...
```

and get a schema

```
hello(input: {}) {
  foo
  bar
}
```

**Comment by w9** [comment]
@benjie And what is smart comments?

**Comment by benjie** [comment]
Yep, OUT keyword is a natural fit definitely. However it's significantly more code to implement - particularly because if you have 2 or more OUT args that's supposed to be equivalent to returning a RECORD(...), so we'd need to declare a new dynamic type for it which we don't have code for currently. (Also this stuff is complex internally in general because of the way PostgreSQL/pg interact over these types.)

However, simply renaming something that already exists in the codebase is much MUCH less code.

Smart comments:

https://github.com/postgraphql/postgraphql/issues/473#issuecomment-314713154

https://github.com/graphile/graphile-build/pull/128

**Comment by w9** [comment]
@benjie Thanks. Can you point to me places I might be interested to look at if I were to start working on the OUT keyword?

**Comment by benjie** [comment]
This is used for all the procedures (mutations, computed fields, everything):

https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/plugins/makeProcField.js

Currently we just use the return type:

https://github.com/graphile/graphile-build/blob/552148e238475c95839e0d5fb3147d08868f3fd5/packages/graphile-build-pg/src/plugins/makeProcField.js#L100

However you're going to want to poke around in the introspection results and figure out how to extract the various OUT / INOUT args.

If there's more than one of these, then you're going to want to generate a new type for this. It'll probably have to be named after the function, so for example `HelloResult` or `HelloReturnType` for the `hello` function above. For naming this, add an inflector to `inflections.js`. You can probably get away with defining that type in the same `makeProcField` file since it will be specific to that function.

If a computed field uses OUT you may need to tweak the name a bit more so it's sensible and won't cause clashes in future.

This is the plugin that adds query procedures (such as `hello` and `hello2` above) to the schema:

https://github.com/graphile/graphile-build/blob/552148e238475c95839e0d5fb3147d08868f3fd5/packages/graphile-build-pg/src/plugins/PgQueryProceduresPlugin.js

Most likely the try/catch block is catching an error from `makeProcField` currently?

https://github.com/graphile/graphile-build/blob/552148e238475c95839e0d5fb3147d08868f3fd5/packages/graphile-build-pg/src/plugins/PgQueryProceduresPlugin.js#L69-L83

It's 11:20pm here now, I'm off to bed. Let me know how you get on, and when you want more hints.

**Comment by w9** [comment]
@benjie Thanks again. Great guide. I will start by looking at the `makeProcField.js` and will let you know how it goes.

**Comment by benjie** [comment]
@mattbretl Is now fixing this as part of https://github.com/graphile/graphile-engine/pull/296
