### ISSUE TITLE
`graphql-parse-resolve-info` : typescript issue

### ISSUE THREAD

**Issue by amedeedaboville** [graphile/graphile-engine#344]
Hi, thanks for Postgraphile!

I'm sorry to post this because it's a typescript issue, and I don't know the exact fix... Though it's most likely a version issue somewhere.

When using `postgraphile@latest` (or 4.0.1) in `typescript@3.1.6` (the latest), `tsc` fails with:
```
node_modules/graphql-parse-resolve-info/node8plus/index.d.ts:2:16 - error TS2665: 
Invalid module name in augmentation.
Module 'graphql/type/definition.js' resolves to an untyped module at 
 '.../node_modules/graphql/type/definition.js', which cannot be augmented.
```

The offending lines seem to be [graphql-parse-resolve-info/src/index.ts:](https://github.com/graphile/graphile-engine/blob/master/packages/graphql-parse-resolve-info/src/index.ts#L24-L29)

```
// Extend GraphQLResolveInfo for old GraphQL versions
declare module "graphql/type/definition.js" {
  interface GraphQLResolveInfo {
    readonly fieldASTs: ReadonlyArray<FieldNode>;
  }
}
```
as when I comment them out the tsc error goes away. The graphql version installed by `npm` is either `0.13.2` in `postgraphile@4.0.1` or `14.0.2` in latest. I'm guessing newer versions of GraphQL don't allow for being extended?

For now I have excluded `node_modules` from my `tsconfig.json` but am just submitting this so you're aware (or to find out if I've misconfigured something). I made a repro [here](https://github.com/amedeedaboville/postgraphile-tsissue).

**Comment by benjie** [comment]
Might be best for us to solve this by using `// @ts-ignore` instead of defining the type. It's there for backwards compatibility with an older GraphQL version. It's these two lines that are the problem:

https://github.com/graphile/graphile-engine/blob/61957931d236b78c0c8791420d052ae8af22aecf/packages/graphql-parse-resolve-info/src/index.ts#L87-L88

https://github.com/graphile/graphile-engine/blob/61957931d236b78c0c8791420d052ae8af22aecf/packages/graphql-parse-resolve-info/src/index.ts#L110-L111

Perhaps:

```js
let asts: ReadonlyArray<FieldNode> = resolveInfo.fieldNodes;
// @ts-ignore
if (!asts) asts = resolveInfo.fieldASTs;
```
