### ISSUE TITLE
Bad pluralizations for special pluralize cases

### ISSUE THREAD

**Issue by jgzuke** [graphile/graphile-engine#471]
For any [special cases](https://github.com/blakeembrey/pluralize/blob/master/pluralize.js#L273) in pluralize, if your table name contains more than one word they will get pluralized incorrectly. For example the table `species` would show up in the schema as singular type `Species`, but the table `plant_species` would show up as type `PlantSpecy`.

**Comment by benjie** [comment]
Any bad pluralisations can be fixed by overriding the pluralize/singularize inflectors using makeAddInflectorsPlugin: https://graphile.org/postgraphile/make-add-inflectors-plugin

You may also be interested in the `distinctPluralize` feature I added to `pg-simplify-inflector`: https://github.com/graphile-contrib/pg-simplify-inflector/blob/94cb288beefef876c91a9f4ee7f0ab8999a55186/index.js#L51-L70

Unfortunately this cannot be fixed in core as it will break peoples existing schemas. Thank you for raising the issue nonetheless 👍

**Comment by ab-pm** [comment]
I have the same problem (with a table name containing `series`). How exactly can I use that `distinctPluralize` method? Do I need to skip the `simplify-inflector` plugin and write my own, or should I add another plugin that somehow hooks into the `simplify-inflector`?

**Comment by benjie** [comment]
Just add another inflector plugin after simplify that overwrites `distinctPluralize`. All the inflector plugins just overwrite (or add) individual inflection methods, that's why they use `this` so they can refer to the very latest version (after all the overwrites).

**Comment by ab-pm** [comment]
Thanks, looks like I need to get more familiar with the plugin system. I thought [hooks](https://www.graphile.org/graphile-build/hooks/) were just called when schema entities are created, but didn't really understand what the `extend` stuff does - so the plugins are ran on a builder for an object before it is actually built (and thereby can overwrite each others methods)? But who then calls these methods in the end, where is that documented? Especially with [`makeAddInflectorsPlugin`](https://github.com/graphile/graphile-engine/blob/master/packages/graphile-utils/src/makeAddInflectorsPlugin.ts) I am lost, as the `"inflection"` hook is not documented anywhere…
(Sorry for getting off-topic on this thread, I can open an other question issue if you want).

**Comment by benjie** [comment]
> I thought hooks were just called when schema entities are created

Correct.

>  didn't really understand what the extend stuff does

`extend(a, {b: 2})` is roughly equivalent to `Object.assign(a, {b: 2})` but with a tonne of extra built in protections and logging when fields conflict.

> so the plugins are ran on a builder for an object before it is actually built (and thereby can overwrite each others methods)?

We start with an inflectors object that's something like `{pluralize, singularize, camelCase}`.

Hooks get called on the result of each other to calculate the final value, so you can think of it as:

```js
const initialInflectors = {pluralize, singularize, camelCase}; // Supplied by graphile-build

const finalInflectors =
  hook3( // Your Hook Here
    hook2( // from @graphile-contrib/pg-simplify-inflector
      hook1( // from graphile-build-pg
        initialInflectors
      )
    )
  );
```

In this situation you might have that `hook1` is the `graphile-build-pg` hook that adds all the PG-specific inflectors (`graphile-build` doesn't care about PG), `hook2` is the simplify inflector's hook, so you need to implement `hook3` to augment that with your mods.

> But who then calls these methods in the end, where is that documented?

`graphile-build` (aka Graphile Engine) is responsible for managing the calling of all the hooks. They all execute synchronously. They start here:

https://github.com/graphile/graphile-engine/blob/2c0ce76c55fe2208c1445534f1904b3844a771d2/packages/graphile-build/src/SchemaBuilder.js#L476-L493

> Especially with makeAddInflectorsPlugin  I am lost, as the "inflection" hook is not documented anywhere…

You shouldn't need to even worry about any of this, the `makeAddInflectorsPlugin` ([documented here](https://www.graphile.org/postgraphile/make-add-inflectors-plugin/)) should completely abstract the whole hook system so you only need to worry about writing your override:


```js
const { makeAddInflectorsPlugin } = require("graphile-utils");

module.exports = makeAddInflectorsPlugin({
  allRows(table: PgClass) {
    return this.camelCase(
      `all-${this.distinctPluralize(this._singularizedTableName(table))}`
    );
  },
}, true);
```

---

Help with improving the documentation is _always_ welcome, so once you've worked it out if you can contribute back your learnings (or even just write up in a better way what I've scribbled above) into the docs, that would be very helpful :pray:

**Comment by ab-pm** [comment]
Ah, thank you for the extensive answer.
I didn't really realise that an inflector object is built by such a series of hooks as well. I think the [all-hooks page](https://www.graphile.org/graphile-build/all-hooks/) (which doesn't list any more hooks than the [hooks page](https://www.graphile.org/graphile-build/hooks/)?) should document this, currently it can only be found in the source https://github.com/graphile/graphile-engine/blob/86ef40f0591c5580c6af38c4baf5f6f270dfbd2d/packages/graphile-build/src/SchemaBuilder.js#L162-L164

What you didn't answer yet is how to find out which inflection method to overwrite when I have a problem with a particular name (and an `@name` comment is not enough to fix it, because even the tagged name gets inflected). The hook system is wonderfully flexible, but makes it very hard to figure out which methods are called from where (and in what order). I did find [the docs about what inflection methods there are](https://www.graphile.org/postgraphile/make-add-inflectors-plugin/#where-are-the-default-inflectors-defined), but it would be super-useful if you could add an overview of the "call graph" for constructing any entity's name. Or are they really just the default ones and those from pg-simplify-inflector, and one needs to read those codes and take a guess based on the method name?

**Comment by benjie** [comment]
> should document this

Yes it should; the graphile-engine docs are quite out of date because I've been focussed on the PostGraphile docs. Would you be interested in raising a PR to add docs for this (and any other) missing hook? I'm not sure if `init` or `finalize` (used by `makeProcessSchemaPlugin` I think) are documented either.

> The hook system is wonderfully flexible, but makes it very hard to figure out which methods are called from where (and in what order). 

Indeed, this is an ongoing problem. The solution needs to be automated, but I've not come up with it yet. Currently your best bet is scanning through a likely candidate from the list, and then searching to see where that's used in the graphile-engine source. This is a far from ideal situation, but I'm yet to know how to solve it. I'm hoping with the move to TypeScript I'll be able to introspect the types and generate documentation from them somehow...?

**Comment by benjie** [comment]
BTW the original aim of the hook system was to make it so you don't have to fork PostGraphile to make the changes you want to make; so the idea was if you've tracked down the line of code you want to edit you should be able to apply that edit then via hooks - at this point you'd already know which inflectors/scope/etc you need. But now people are using hooks/plugin helpers more I need to make these more user friendly for people who aren't looking to do extensive source-diving, and that's currently an unsolved problem.
