### ISSUE TITLE
Typescript migration issues/ideas

### ISSUE THREAD

**Issue by ab-pm** [graphile/graphile-engine#585]
Hi, I'm trying 4.6.0-alpha and looking to properly type my plugins. Here are my findings:

* please expose the `stringTag` function - I want to use it in my custom inflection
* referencing one of the other inflection methods  (except for the basic ones apparently) from inside a new inflection method didn't work easily because the type of `this` is `Partial<Inflection>`, apparently inferred from the type of `inflection` itself that I spread in the same object literal. I did work around this by declaring `this: Inflection` in the method, is this the proper solution?
* Similarly, referencing `build.pgIntrospectionResultsByKind` in the `build` hook does obviously complain because it *might* not be there (which is correct, depends on the order of plugins), however that I could fix with a non-null assertion (`!`) because its type is `| undefined` not `| void`.
* `PgConstraint` could be made more specific by having non-optional `foreign…` properties if the `type` is `'f'`, using a tagged union? Or a `PgForeignConstraint` subtype? Or something like that.
* I feel like it would be a great simplification (also of the graphile-build-pg codebase itself) if `pgGetGqlTypeByTypeIdAndModifier` would never return `null` and instead throw an error when no registered type could be found. For the few cases that need to test whether it exists or not, provide a separate method.
* `build.extend` was [not documented with the `hint` string](https://www.graphile.org/graphile-build/build-object/#extendinput-extensions), but it has become compulsory now in the method signature. Not sure whether this was on purpose, I guess it is a good thing though and should be fixed in the documentation rather than making the type option?
* previously valid `graphileBuildOptions` don't work any more: https://github.com/graphile/pg-simplify-inflector/issues/27
* The [new `GraphileResolverContext`](https://github.com/graphile/postgraphile/pull/1205) is much more useful than the [old `PostgraphileContext`](https://github.com/graphile/postgraphile/blob/8a9852f7e9c1a729ed4d95e2a46eaea0c8a9872d/src/postgraphile/withPostGraphileContext.ts#L16-L19), thanks!
* I'm missing something similar for the `ResolveInfo` type that [is augmented in the `makeExtendSchemaPlugin`](https://github.com/graphile/graphile-engine/blob/9bbf0f543ec88ef1ae54c30d56db22f3e4a6d055/packages/graphile-utils/src/makeExtendSchemaPlugin.ts#L35-L37). Would be really useful if that type was exported on the top level so that I can explicitly use it to declare parameters. Also, the [`TContext` parameter is left to `any` in the `ExtensionDefinition`](https://github.com/graphile/graphile-engine/blob/9bbf0f543ec88ef1ae54c30d56db22f3e4a6d055/packages/graphile-utils/src/makeExtendSchemaPlugin.ts#L71) while it should be `GraphileResolverContext`.

**Comment by benjie** [comment]
> please expose the stringTag function - I want to use it in my custom inflection

This seems a reasonable request; please open a PR.

>  I did work around this by declaring this: Inflection in the method, is this the proper solution?

Yes.

> is `| undefined` not `| void`.

I think `flow2typescript` did `| void`  rather than `| undefined` in quite a lot of places. I'm happy changing them all to `| undefined`, I'm not sure why you'd really want `| void` in a union type in most cases. (I guess `void` is technically more correct here since the property literally doesn't exist, but :man_shrugging:.) You can work around this with `if (!('pgIntrospectionResultsByKind' in build)) throw new Error(":-(");`

> `PgConstraint` [...] using a tagged union

Yeah; I actually looked at doing this (we'd want named union because we'd want to refer to the different constraints separately), but I spent 6 days on the TypeScript conversion in the end and the number of errors this introduced broke my will to spend any more time on it. In the end I changed the introspection query instead - making it so that certain fields were empty arrays rather than null as they would be in postgres.

If we do this for constraints we should also do it for other entities too, such as PgClass which could differentiate between type vs table vs view vs materialized view, etc.

I'm not planning to make these changes any time soon; I've spent far too long on the TypeScript conversion already.

> `pgGetGqlTypeByTypeIdAndModifier`  would never return `null` and instead throw an error 

Yeah; but that'd be a breaking change.

> build.extend was not documented with the hint string, but it has become compulsory now in the method signature. Not sure whether this was on purpose, I guess it is a good thing though and should be fixed in the documentation rather than making the type option?

I'm on the fence with this. Internally I want to always ensure it's specified. If we could expose different typings externally I'd be open to that... But honestly this release breaks pretty much all the TypeScript typings so this is the least of my concerns. I'm currently thinking I should push the TypeScript changes out in v5 rather than 4.6.

> previously valid graphileBuildOptions don't work any more

They work fine in JS. In TypeScript it's gone from a `[key: string]: any` map to a strict object... There's no way around that if we want stronger typings I think?

> The new GraphileResolverContext is much more useful than the old PostgraphileContext, thanks!

Did I remember to make `PostgraphileContext` an alias to `GraphileResolverContext` for backwards compatibility? Doesn't really matter if we push this all to v5.

> I'm missing something similar for the ResolveInfo type that is augmented in the makeExtendSchemaPlugin.

How would you implement this?

> Also, the TContext parameter is left to any in the ExtensionDefinition while it should be GraphileResolverContext.

PR welcome :+1:

**Comment by ab-pm** [comment]
OK, I'll work on a PR. Another point I just noticed:

* `ArgDataGeneratorFunction` and `DataGeneratorFunction` should be allowed to return nothing

**Comment by benjie** [comment]
> ArgDataGeneratorFunction and DataGeneratorFunction should be allowed to return nothing

:man_shrugging: Returning `{}` is easy enough, and preferably you should just not add the data generator if you're not going to return anything.

> (I wonder why the generator could not simply be called during the init phase?)

`master` is now the working branch for v5, I'm going to forbid type construction during the `build` phase. In fact I want to completely forbid type construction in general, instead make people register type generators that are called on demand. I've not figured out how to handle the "no fields" issue currently though.

**Comment by benjie** [comment]
Closing this as V5 is now TypeScript everywhere. It's still a while away from release though.

**Comment by Venryx** [comment]
Is a Typescript-everywhere version of graphile-engine (ie. V5) still in the works?

I'm confused as there are four branches (v4, v5, v5-wip, master), and I don't know which of those represents the "cutting edge".

Also, when I check the NPM versions, I don't see anything for V5 (even alpha/beta versions): https://www.npmjs.com/package/postgraphile?activeTab=versions

The reason I'm interested is that I'm looking to extend the [subscription-lds](https://github.com/graphile/graphile-engine/tree/v4/packages/subscriptions-lds) package with additional features (eg. optimization to only have the _delta_ transmitted to clients, when a collection-query's result changes), and having the complete TS typings would let me explore the codebase more efficiently.

**Comment by benjie** [comment]
The latest _public_ v5 branch is https://github.com/graphile/postgraphile/tree/v5 (note it merges everything into a single monorepo), which may serve your exploration needs.

My plans for v5 have diverged a bit from that; I have a private branch that I'm working on actively, I'm not yet ready to share what I'm working on because I'm not 100% sure it's even possible... But the reality seems to be getting closer. I will open source it when I'm ready to deal with all the questions about how it works, why, etc etc. I can't answer all those questions to myself yet, let alone other people :wink:, so open sourcing it at this stage would simply reduce my availability to work on it.
